name: Train Random Forest

on:
  workflow_dispatch:   # puedes lanzarlo manualmente
  push:
    paths:
      - "train_rf.py"
      - "data/processed/**"

permissions:
  contents: write   # necesario para hacer commits

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: |
          python train_rf.py

      - name: Commit and push trained model
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/metadata/random_forest_model.pkl
          git commit -m "Update trained Random Forest model [skip ci]" || echo "No changes to commit"
          git push
