name: Update KOI Data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"  # cada domingo a medianoche UTC

permissions:
  contents: write   # 👈 Permiso para escribir en el repo

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update script
        run: python update_koi_data.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/
          git commit -m "📡 Auto-update KOI data" || echo "No changes to commit"
          git push
