name: Update KOI Data

# Se puede ejecutar manualmente o programado (cron)
on:
  workflow_dispatch:           # para correr manual
  schedule:
    - cron: "0 8 * * *"       # todos los días a las 08:00 UTC

# Permisos necesarios para escribir en el repo
permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Obtener el repositorio
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyarrow
          pip install pyarrow fastparquet


      # 4️⃣ Ejecutar script de actualización
      - name: Run update script
        run: python update_koi_data.py

      # 5️⃣ Commit y push de los cambios
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/
          git commit -m "📡 Auto-update KOI data $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
